### ISSUE TITLE
Possible issue with function pairwise_rf_estimation

### ISSUE THREAD

**Issue by peterbourke** [mmollina/Autopolyploid_Linkage#1]
Hi Marcelo,

Just trying to run MAPpoly and I'm stuck at the step in the potato Vignette (using my own test dataset) est_pairwise_rf. I get the following error message:

INFO: Using  7  CPUs for calculation.
Error in checkForRemoteErrors(val) : 
  7 nodes produced errors; first error: "pairwise_rf_estimation" not available for .Call() for package "mappoly"

I had a look around in mappoly:: and mappoly::: and couldn't see the function. The steps up to then worked fine. My test data is nothing strange I think. Was wondering whether the previous step cache_counts_twopt assumed I was using the Vignette data (although the object seq.unique was created using my own data).

Many thanks, and happy Christmas,

Peter

**Comment by mmollina** [comment]
Hello Peter, 

Thanks for pointing that out.  Would it be possible for you to send a minimal reproducible example, so I can try to figure out what is happening?

Thanks you and happy holidays!
Marcelo

**Comment by peterbourke** [comment]
Hi Marcelo,
Thanks for getting back so quickly. Attached is the data I was trying it with, from an autotetraploid population with about 60 markers from a single linkage group (already mapped in polymapR). 

[debug_files.zip](https://github.com/mmollina/Autopolyploid_Linkage/files/3989093/debug_files.zip)

Cheers,
Peter

**Comment by mmollina** [comment]
Great, 
I will work on it and get back to you as soon as possible. 
Thanks

**Comment by mmollina** [comment]
Hi Peter,

I tried to reproduce the error on my Linux box and also using a fresh R + Rstudio + mappoly installation on a Windows machine. In both cases, the program worked just fine.

"pairwise_rf_estimation" is a CPP function, and for some reason, its shared object (DLL or SO) is not available in your installation. Also, even if the function was working, it is not expected to find "pairwise_rf_estimation" at mappoly namespace (since "pairwise_rf_estimation" is a CPP function).

My advice would be to install the latest version of Rtools35.exe, which contains the CPP compiler for Window and try to reinstall mappoly with

devtools::install_github("mmollina/mappoly", force = TRUE)

please let me know if it worked.
Marcelo

**Comment by peterbourke** [comment]
Hi Marcelo,
Yes that solved this issue. Many thanks for the help.
Best regards,
Peter
